### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by jannar85** [Konsl/spicetify-extensions#3]
The function doesn't work anymore (find-duplicates). It doesn't do anything.

**Comment by stebo02** [comment]
It has been working for me but only until a recent update in february

**Comment by Konsl** [comment]
Does 725f80b resolve this issue?

**Comment by stebo02** [comment]
For me it still doesn't show the "find duplicates" menu option, nor the "+1" etc. next to the heart

**Comment by stebo02** [comment]
Nevermind, it's working again. Thanks a lot!
